### ISSUE TITLE
Proposal of Web-Scale Bayesian CTR Predictor paper by Microsoft

### ISSUE THREAD

**Issue by d-khokhlov** [wnzhang/rtb-papers#16]
Consider to add the following paper:

Web-Scale Bayesian Click-Through Rate Prediction for Sponsored Search Advertising in Microsoft’s Bing Search Engine (Thore Graepel, Joaquin Quiñonero Candela, Thomas Borchert, Ralf Herbrich, 2010)
https://www.microsoft.com/en-us/research/wp-content/uploads/2010/06/AdPredictor-ICML-2010-final.pdf

Also consider this python implementation of the AdPredictor algorithm described in the paper above:
http://tullo.ch/articles/online-learning-with-adpredictor/

**Comment by wnzhang** [comment]
Thanks but this is for search advertising (sponsored search) instead of RTB display advertising.
