### ISSUE TITLE
Do you know any implementation of the algorithm proposed in "Using Co-Visitation Networks For Classifying Non-Intentional Traffic"

### ISSUE THREAD

**Issue by wenmin-wu** [wnzhang/rtb-papers#9]
Recently, I want to implement the algorithm proposed in "Do you know any implementation of the algorithm proposed in "Using Co-Visitation Networks For Classifying Non-Intentional Traffic". It's hard to start from scratch, and it will be easier if there is any implementation to follow. If you know, please tell me. Thx!

**Comment by ulutech** [comment]
My research team mate in SJTU has the code. If interested, please send me an email for discussion. Many thanks.

**Comment by wnzhang** [comment]
My research team mate in SJTU has the code. If interested, please send me an email for discussion. Many thanks.

**Comment by wenmin-wu** [comment]
@wnzhang I'm very interested in the implementation of this algorithm, can you give you email address to me?

**Comment by wnzhang** [comment]
w.zhang@cs.ucl.ac.uk  thanks.

**Comment by wenmin-wu** [comment]
I have shared my implementation of this algorithm in [rtb-algorihtms](https://github.com/wenmin-wu/rtb-algorithms).

**Comment by wnzhang** [comment]
Good to see that. Thanks.
